CREATE TABLE Person
(
  Name_and_Surname CHAR NOT NULL,
  Hometown CHAR NOT NULL,
  Date_of_Birth DATE NOT NULL,
  Date_of_Death DATE,
  #PERSON_ID INT NOT NULL,
  PRIMARY KEY (#PERSON_ID)
);

CREATE TABLE Political_Party_Leader
(
  #LEADER_ID INT NOT NULL,
  Date_Started DATE NOT NULL,
  Date_Ended DATE NOT NULL,
  #PERSON_ID INT NOT NULL,
  PRIMARY KEY (#LEADER_ID),
  FOREIGN KEY (#PERSON_ID) REFERENCES Person(#PERSON_ID),
  UNIQUE ()
);

CREATE TABLE Presidental_Election
(
  Date DATE NOT NULL,
  Total_People_Who_voted INT NOT NULL,
  Turnout FLOAT NOT NULL,
  PE_ID INT NOT NULL,
  PRIMARY KEY (PE_ID)
);

CREATE TABLE Political_Party
(
  Name CHAR NOT NULL,
  Foundation_Date DATE NOT NULL,
  Dissolution_Date DATE,
  PARTY_ID INT NOT NULL,
  #LEADER_ID INT NOT NULL,
  PRIMARY KEY (PARTY_ID),
  FOREIGN KEY (#LEADER_ID) REFERENCES Political_Party_Leader(#LEADER_ID)
);

CREATE TABLE Presidantal_Candicate
(
  PRESIDENTAL_CAND_ID INT NOT NULL,
  Result FLOAT NOT NULL,
  #PERSON_ID INT NOT NULL,
  PARTY_ID INT NOT NULL,
  PE_ID INT NOT NULL,
  PRIMARY KEY (PRESIDENTAL_CAND_ID),
  FOREIGN KEY (#PERSON_ID) REFERENCES Person(#PERSON_ID),
  FOREIGN KEY (PARTY_ID) REFERENCES Political_Party(PARTY_ID),
  FOREIGN KEY (PE_ID) REFERENCES Presidental_Election(PE_ID)
);

CREATE TABLE Presidental_Election_Winner
(
  PEW_ID INT NOT NULL,
  PE_ID INT NOT NULL,
  PRESIDENTAL_CAND_ID INT NOT NULL,
  PRIMARY KEY (PEW_ID),
  FOREIGN KEY (PE_ID) REFERENCES Presidental_Election(PE_ID),
  FOREIGN KEY (PRESIDENTAL_CAND_ID) REFERENCES Presidantal_Candicate(PRESIDENTAL_CAND_ID)
);

CREATE TABLE General_Election_Result
(
  #RESULT_ID INT NOT NULL,
  Percantage FLOAT NOT NULL,
  Seat INT NOT NULL,
  PARTY_ID INT NOT NULL,
  #GENERAL_ELECTION_ID INT NOT NULL,
  PRIMARY KEY (#RESULT_ID),
  FOREIGN KEY (PARTY_ID) REFERENCES Political_Party(PARTY_ID),
  FOREIGN KEY (#GENERAL_ELECTION_ID) REFERENCES General_Election(#GENERAL_ELECTION_ID)
);

CREATE TABLE General_Election
(
  #GENERAL_ELECTION_ID INT NOT NULL,
  Date CHAR NOT NULL,
  Total_People_Who_voted INT NOT NULL,
  Turnout FLOAT NOT NULL,
  #RESULT_ID INT NOT NULL,
  PRIMARY KEY (#GENERAL_ELECTION_ID),
  FOREIGN KEY (#RESULT_ID) REFERENCES General_Election_Result(#RESULT_ID)
);